### ISSUE TITLE
Can i disable  "no sources required" in the above the fold optimization?

### ISSUE THREAD

**Issue by bronze** [divriots/jampack#101]
Hi
Is there an option available to disable the `JPEG in picture tag => no sources required` function when optimizing above the fold?
I set up an image with different sizes for different breakpoints and jampack is choosing the lowest one to display so Pagespeed then complains about the image being too small.
I'd like to use everything else. Changing loading and fetchpriority sound great. I'd just like to keep my different sources.

Fom: 
``` 
   <picture><source type="image/avif" srcset="data:image/avif;base64,AAAAHGZ...UYhKY= 300w, /assets/CNt-PnDVr4-600-611e33c6.avif 600w, /assets/CNt-PnDVr4-800-1c040ee0.avif 800w" sizes="(min-width: 66em) 33vw, (min-width: 44em) 50vw, 100vw"><source type="image/webp" srcset="/assets/CNt-PnDVr4-300-22037960.webp 300w, /assets/CNt-PnDVr4-600-faf01c02.webp 600w, /assets/CNt-PnDVr4-800-3999a53a.webp 800w" sizes="(min-width: 66em) 33vw, (min-width: 44em) 50vw, 100vw"><source type="image/png" srcset="/assets/CNt-PnDVr4-300-7e7401a9.png 300w, /assets/CNt-PnDVr4-600-658bcd90.png 600w, /assets/CNt-PnDVr4-800-1aa0fa89.png 800w" sizes="(min-width: 66em) 33vw, (min-width: 44em) 50vw, 100vw"><img class="aspect-[1.78]" alt="Test" loading="lazy" decoding="async" src="/assets/CNt-PnDVr4-300-7e7401a9.png" width="800" height="450"></picture>
```
To:
``` 
<picture><img alt="Test" class="aspect-[1.78]" decoding="async" height="450" src="/assets/CNt-PnDVr4-300-7e7401a9.png.jpg" width="800" fetchpriority="high"></picture>
```

Thanks

**Comment by georges-gomes** [comment]
No option yet.
But the current implementation is maybe too aggressive.
It should probably not delete the other sources...

**Comment by georges-gomes** [comment]
Made the change and `jampack` is not deleting the original source. Above-the-fold or below-the-fold.
Next step will be to better optimise existing `<source>` elements in `<picture>`.

Thanks for reporting 🙏
