### ISSUE TITLE
Feature request: add a custom cache directory

### ISSUE THREAD

**Issue by edheltzel** [divriots/jampack#106]
It would be nice if there was a way to create a custom cache directory through either a config or using the cli. 

My use case is with Cloudflare Pages - currently in beta, but you can enable [build caching](https://developers.cloudflare.com/pages/platform/build-caching/#frameworks), which currently supports:

Framework | Directories cached
-- | --
Gatsby | .cache, public
Next.js | .next/cache
Astro | node_modules/.astro

My current workaround is to build locally and then use `wrangler` to deploy manually.

**Comment by georges-gomes** [comment]
Hi! 

I didn't know about this new "build caching". Well done Cloudflare. Thanks for bringing it up.

New `jampack` version released `0.21.0` to support a new CLI option:
`--cache_folder`
By default the value is `.jampack/cache`

**Comment by edheltzel** [comment]
@georges-gomes appreciate the info on `0.21.0` I'm not sure if I'm doing something wrong here, but I'm getting and error:

```shell
npx @divriots/jampack ./_site --cache_folder='.cache'
     __                                    __    
    |__|____    _____ ___________    ____ |  | __
    |  \__  \  /     \\____ \__  \ _/ ___\|  |/ /
    |  |/ __ \|  Y Y  \  |_> > __ \\  \___|    < 
/\__|  (____  /__|_|  /   __(____  /\___  >__|_ \
\______|    \/      \/|  |       \/     \/     \/
 v0.21.0              |__| by ‹div›RIOTS

Options:
{ cache_folder: '.cache' }

Failed to create `_jampack` folder.
====================== second try 👇 =====================
npx @divriots/jampack ./_site --cache_folder '.cache'
     __                                    __    
    |__|____    _____ ___________    ____ |  | __
    |  \__  \  /     \\____ \__  \ _/ ___\|  |/ /
    |  |/ __ \|  Y Y  \  |_> > __ \\  \___|    < 
/\__|  (____  /__|_|  /   __(____  /\___  >__|_ \
\______|    \/      \/|  |       \/     \/     \/
 v0.21.0              |__| by ‹div›RIOTS

Options:
{ cache_folder: '.cache' }

Failed to create `_jampack` folder.
```

**Comment by georges-gomes** [comment]
Sorry about that, silly mistake. `0.21.1` should fix it.
Let me know how it goes! 🙏

**Comment by edheltzel** [comment]
@georges-gomes, that did it! Again appreciate you getting a release out "blazingly fast"
