### ISSUE TITLE
Allow consumption through Deno

### ISSUE THREAD

**Issue by bebraw** [divriots/jampack#118]
Ideally you should be to do `import * as jampack from "npm:@divriots/jampack@0.22.1";`. In my quick test that gave the following:

```
error: Uncaught (in worker "") (in promise) TypeError: Could not resolve 'npm:@divriots/jampack@0.22.1'.(463/464)
  Caused by:
    Failed resolving package subpath '.' for '/Users/juhovepsalainen/Library/Caches/deno/npm/registry.npmjs.org/@divriots/jampack/0.22.1/package.json'
    [ERR_PACKAGE_PATH_NOT_EXPORTED] No "exports" main defined in '/Users/juhovepsalainen/Library/Caches/deno/npm/registry.npmjs.org/@divriots/jampack/0.22.1/package.json' imported from '/Users/juhovepsalainen/Projects/github/gustwindjs/gustwind/plugins/jampack/mod.ts'
```

If you want to try, you can find the related code at https://github.com/gustwindjs/gustwind/pull/126 . After pulling, run `deno task build` to see the error. I used Deno 1.38.2 for testing.

Looking at the code, I can see the project is using an older version of Sharp that doesn't support Deno yet. Here's a bit more info on how to get it going: https://github.com/lovell/sharp/issues/3750#issuecomment-1751172728 . The version that worked for me is `npm:sharp@0.33.0-rc.2`. Based on the error, it's possible there's something else to amend as well and I understand if you want to wait for a stable 0.33.0.

On a related note, it would be nice if you could document how to use the API as a JavaScript module although it's quite trivial to figure out anyway.

**Comment by bebraw** [comment]
@oliverpool Nice, thanks. I can confirm it works now. I was able to drop npm from my little project after this. 👍

**Comment by oliverpool** [comment]
However for some reason it hangs at the very end, after printing `✔ No issues`.

So I have pipe a dummy comment to it: `echo "exit when done" | deno run -A --unstable npm:@divriots/jampack ./_site`

**Comment by bebraw** [comment]
Ok, I didn't see the hang in my use case.

Maybe you can reduce a small example and open a separate issue to debug as it could be some specific combination.
