### ISSUE TITLE
Feature Request: Add support for browser targets

### ISSUE THREAD

**Issue by morrisonsign** [divriots/jampack#119]
I'd like lightningcss to process based on a [browser target](https://lightningcss.dev/transpilation.html).

It would be nice if a browser target could be added via configuration, which would take a [browserlist](https://github.com/browserslist/browserslist) value and use it when processing through lightningcss.

**Comment by georges-gomes** [comment]
Hi @morrisonsign 

Thanks for reporting this.
It's now available in version `0.23.0`.

More details here:
https://jampack.divriots.com/features/browser-compatibility/

Let me know how it goes.
Cheers
