### ISSUE TITLE
No source generated for `<picture>` tag

### ISSUE THREAD

**Issue by oliverpool** [divriots/jampack#135]
According to the [documentation about `<picture>` tags](https://jampack.divriots.com/features/optimize-images/#picture-tags), 

```html
<picture>
    <img src="./redpanda.jpg" alt="Red panda">
</picture>
```

should become

```html
<picture>
    <source type="image/avif" srcset="./redpanda@1936w.avif 1936w, ./redpanda@1636w.avif 1636w, ./redpanda@1336w.avif 1336w, ./redpanda@1036w.avif 1036w, ./redpanda@736w.avif 736w">
    <source type="image/webp" srcset="./redpanda@1936w.webp 1936w, ./redpanda@1636w.webp 1636w, ./redpanda@1336w.webp 1336w, ./redpanda@1036w.webp 1036w, ./redpanda@736w.webp 736w">
    <img src="./redpanda.jpg" alt="Red panda" loading="lazy" decoding="async" width="1936" height="1296" srcset="./redpanda.jpg 1936w, ./redpanda@1636w.jpg 1636w, ./redpanda@1336w.jpg 1336w, ./redpanda@1036w.jpg 1036w, ./redpanda@736w.jpg 736w" sizes="100vw">
</picture>
```

However the picture is generated without any `<source ...>`:

```html
    <picture>
      <img src="./picture_redpanda.jpg.jpg" alt="Red panda" fetchpriority="high" decoding="async" width="1936" height="1296" srcset="./picture_redpanda.jpg.jpg 1936w, ./picture_redpanda@1636w.jpeg 1636w, ./picture_redpanda@1336w.jpeg 1336w, ./picture_redpanda@1036w.jpeg 1036w" sizes="100vw">
    </picture>
```

https://jampack.divriots.com/features/optimize-images/packed/index.html

---

Furthermore the `src` and the first image of the `srcset` have redundant extensions.

**Comment by georges-gomes** [comment]
Hi!

I need to fix the redundant extensions.

The image is detected as "above-the-fold" and so progressive jpeg is preferred for good LCP performance.
That's also why the image is not lazy loaded and marked as high priority (`fetchpriority="high"`)
I need to update the test with a very top `<the-fold>` mark.

More details here: https://jampack.divriots.com/features/optimize-above-the-fold/

Thanks for reporting 🙏
I will fix the test file

**Comment by oliverpool** [comment]
To prevent such regression, I had the following idea:

- in [[...feature].astro](https://github.com/divriots/jampack/blob/main/packages/www/src/pages/features/%5B...feature%5D.astro#L38), after the call to `compareSync`
- convert its content to a JSON object
- compare this JSON object with a json file saved in the repo
- if the files differ, overwrite the json file and raise an exception

With this last step, the static site deployment will fail if the "golden json files" are not up to date.
To solve this, generate the static site locally and commit the updated json files until it passes.

**Comment by georges-gomes** [comment]
It's a very good idea as I see these demo equally as tests 👍

**Comment by georges-gomes** [comment]
Test fixed

**Comment by georges-gomes** [comment]
Thanks @oliverpool for reporting 🙏
