### ISSUE TITLE
Hangs with Deno 1.40.5 but works with 1.38.2

### ISSUE THREAD

**Issue by bebraw** [divriots/jampack#138]
I noticed something interesting with Deno usage at https://github.com/ReactFinland/future-frontend-site . The site compiles just fine with Deno `v1.38.2` while it hangs using with `v1.40.5`. I was able to verify this with jampack 0.23.2 and 0.23.3 on my system.

I know it's likely a regression in Deno but I thought to open this issue so Deno users can be aware of the issue.

To push the issue upstream, we likely would have to reduce the demonstration somewhat. One easy option is to wait and see if they fix their hang.

**Comment by georges-gomes** [comment]
New version `0.24.0` with all up-to-date dependencies. Please give it a try 🙏

**Comment by bebraw** [comment]
I tried with Deno `1.42.2` and jampack `0.24.0` and it still hangs for me.

I wonder what could be causing the behavior. Would it help if I could trace down the commit that caused this?

**Comment by georges-gomes** [comment]
I can try and see if I can figure this out.
Thanks for testing 👍

**Comment by plttn** [comment]
FWIW I can still replicate this hang using the jampack docs site: 

https://asciinema.org/a/1exNcXeKjyjzoY6jj5fLtpctk

(17 seconds in is where I go and delete `_jampack` from the folder before running it under Deno).

**Comment by plttn** [comment]
I suspect all that's needed is exiting `exit()` somewhere around here https://github.com/divriots/jampack/blob/08438debb7c253a7dc238a669d13161328608e1d/src/index.ts#L106

When `_jampack` exists, it never hangs and exit is being called there.

**Comment by plttn** [comment]
PR to fix this now open as #195
