### ISSUE TITLE
Vercel + Astro image compressions error

### ISSUE THREAD

**Issue by mradinoff** [divriots/jampack#146]
Turning on Astro's Vercel Adapter option for imageService to true returns can't find img error.

e.g.
Can't find img on disk src="/_vercel/image?examplepath"

**Comment by georges-gomes** [comment]
Hi! Can you share a real life HTML extract with images so I can understand how the Vercel adapter does things here?

**Comment by mradinoff** [comment]
Sure thing, an img in my html output currently looks like this:
 
`<img src="/_vercel/image?url=https%3A%2F%2Fwww.xxxx.com.au%2Fwp-content%2Fuploads%2Fsites%2F2%2F2023%2F08%2Fxxxx_dry_can_noShadow.png&amp;w=640&amp;q=100" title="xxxx_dry_can_noShadow.png" alt="xxxx_dry_can_noShadow.png" loading="lazy" width="auto" height="auto" decoding="async">`

Let me know if there's anything else I can provide to help with this

**Comment by No1ceTea** [comment]
Hello, did you fix the issue ?
If no, can you share me you're astro.config.* ?

**Comment by georges-gomes** [comment]
New release `0.24.4` can exclude some `src` urls.
By default, `/vercel/image?...` is ignored now.
