### ISSUE TITLE
Jampack rotates images 180 degrees

### ISSUE THREAD

**Issue by codemicro** [divriots/jampack#149]
Hiya,

In v0.23.4, I'm running into some weird behaviour where one of my images is being rotated 180 degrees during processing.

I've included the image in question as a minimum example in the example repository below - as far as I can tell, this is the only image that this has happened to in my site.

[codemicro/jampack-image-rotation-bug](https://github.com/codemicro/jampack-image-rotation-bug)

**Comment by georges-gomes** [comment]
Thanks for the example repo 🙏
I suspect it's coming from `sharp`, I will try to fix it soon.
Is it ok if I add the image on jampack tests?

**Comment by georges-gomes** [comment]
Seems to be easy enough to fix: https://stackoverflow.com/a/58828508

**Comment by codemicro** [comment]
> Is it ok if I add the image on jampack tests?

Go ahead!

**Comment by georges-gomes** [comment]
Fixed, will release soon
Visible here: https://jampack.divriots.com/features/optimize-images/

**Comment by georges-gomes** [comment]
Version `0.24.0` released ⚠️ you will need to trash your folder `.jampack` because your rotated image may be there. I didn't want to bump the cache version just for this. 

Thanks for reporting 🙏

**Comment by codemicro** [comment]
Super, thank you for fixing and thanks for the pointer about deleting the cache :)
