### ISSUE TITLE
Jampack messes up <picture> elements used for "Art direction"

### ISSUE THREAD

**Issue by eanyanwu** [divriots/jampack#153]
By art direction, I mean [when you want to show a certain image on mobile, but a different image on desktop views.](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images#art_direction)

👋🏽  Thanks for the wonderful tool!

I have come across this problem enough times that I thought i should create an issue:

[Here is a reproduction.](https://github.com/eanyanwu/jampack-repro/tree/main)
It is a single html page that shows a tall picture when the screen is narrower than 800px, and shows a long picture otherwise.

**Steps**: 
- Run  `npx @divriots/jampack .` in the directory containing the repro.
- Open index.html in the browser

**Expected**:

The image displayed should switch between being long/tall depending on the viewport size

**Actual**:

The image no longer switches between the two options :/

**Comment by georges-gomes** [comment]
Thanks for reporting. Indeed `jampack` needs to support this use case.
Maybe a short-term solution would be to backoff when `source` and `media` are in the source file already.
Longer-term would be to improve image size on top of it.

**Comment by eanyanwu** [comment]
Wow, thanks for the quick response.

>  Maybe a short-term solution would be to backoff when source and media are in the source file already.

This would solve my immediate problem!

**Comment by eanyanwu** [comment]
Not sure if this helps, but one thing I have found is that manually re-ordering the `source` elements in the browser console seems to temporarily fix the issue (until the page is reloaded). I think it's because the browser picks the first source that matches.

**Comment by georges-gomes** [comment]
Fixed - art direction is kept in higher priority
Visible here: https://jampack.divriots.com/features/optimize-images/

I also need to fix the behavior above the fold.
