### ISSUE TITLE
After running jampack, the site is deoptimized

### ISSUE THREAD

**Issue by bebraw** [divriots/jampack#39]
I tried running the optimizer on futurefrontend.com. Here are the results: https://pagespeed.web.dev/report?url=https%3A%2F%2Ffuturefrontend.com%2F .

After applying jampack (https://github.com/ReactFinland/future-frontend-site/pull/1), the performance went down: https://pagespeed.web.dev/report?url=https%3A%2F%2F1b5b0924.future-frontend-site.pages.dev%2F . LCP went from 1.8s to 4.2s on mobile.

Do you know what might be causing that?

**Comment by georges-gomes** [comment]
Hi! 

I see the opposite when running the pagespeed

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/5250572/215714488-ca409ff6-f77c-40e5-855a-4cdd83cb994d.png">

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/5250572/215714546-529dedd2-cad6-4c82-8398-57ec8ef3ab62.png">

Most of your LCP is coming from the font.
I think, depending how Google Font respond you have different performance.

`jampack` doesn't optimise font loading yet.
It will be coming up soon, specially for Google Fonts, there are easy wins.

**Comment by georges-gomes** [comment]
I will report here when font optimisations are in.

**Comment by bebraw** [comment]
Cool, thanks a lot.

I agree it's definitely the font. In this use case subsetting would make a nice difference.
