### ISSUE TITLE
Add configuration to disable the inlined style

### ISSUE THREAD

**Issue by georges-gomes** [divriots/jampack#51]
Let's use https://github.com/natemoo-re/proload for the configuration file.

Someone asked to opt out of `<style>:where(img){height:auto}</style>`.
Apparently it doesn't play nice with CSP policy. I need to understand why.

**Comment by ChrisEke** [comment]
It relates to CSP resource directive `style-src` which blocks inline <style> unless you either allow `'unsafe-inline'` or provide nonce or hash. A good introduction can be found here: [Content security policy](https://web.dev/csp/#inline-code-is-considered-harmful)

In this particular case `<style>:where(img){height:auto}</style>` will be blocked by: 

> Refused to apply inline style because it violates the following Content Security Policy directive: "style-src 'self'". Either the 'unsafe-inline' keyword, a hash ('sha256-RepmFiU4EHjj9tkceTEaRhFBRMqdrD5k7uob1OpeS+U='), or a nonce ('nonce-...') is required to enable inline execution.


A workaround here, as suggested in the message above, is for the site owner to add the hash to the CSP policy `style-src 'self' sha256-RepmFiU4EHjj9tkceTEaRhFBRMqdrD5k7uob1OpeS+U='`. 

But an option to opt-out of any inline script/styling and just get a suggestion to implement these in a separate stylesheet would be preferable.

**Comment by rietama** [comment]
Ok

**Comment by georges-gomes** [comment]
Configuration has been added.
Inline style can be turned off.

https://github.com/divriots/jampack/commit/007da626f694d92a8a144101075cfe491c5583fa

Thanks @ChrisEke for reporting the CSP issue.

Next step would be to offer the generation of a stylesheet file. For later if requested 👍
