### ISSUE TITLE
Only first image reference gets rewritten

### ISSUE THREAD

**Issue by bebraw** [divriots/jampack#52]
At https://futurefrontend.com/, I have multiple same images (see Ken Wheeler for example). For some reason, jampack rewrites only the first reference at speakers but not the second one at workshop instructors.

You should be able to reproduce the issue against https://github.com/ReactFinland/future-frontend-site . First you have to build the site with `deno task build` and then optimize with `npm run optimize:site` (needs `npm install` first). You can see the output at `/build`.

For me, it would make sense if it used the same image reference for both cases since it's the same image after all.

**Comment by georges-gomes** [comment]
Looks like a bug - I will get back to you shortly

**Comment by georges-gomes** [comment]
It was a bug. Thanks for reporting @bebraw 🙏
Fixed and released in `0.9.4`
