### ISSUE TITLE
Dependabot high severity issue in @divriots/jampack@0.9.4 

### ISSUE THREAD

**Issue by franchb** [divriots/jampack#54]
> @divriots/jampack@0.9.4 requires nth-check@~1.0.1 via a transitive dependency on css-select@1.2.0
No patched version available for nth-check

https://github.com/franchb/blog/security/dependabot/1

**Comment by georges-gomes** [comment]
Coming from `cheerio`... Time for another parser...

**Comment by georges-gomes** [comment]
This is now fixed in `0.11.+` with upgrade of `cheerio`.
Thanks for reporting.
