### ISSUE TITLE
add srcset_max_width

### ISSUE THREAD

**Issue by silveltman** [divriots/jampack#74]
I would love to be able to configure max-width of an image. Let's say a photographer provides me with large images (6000px), I like the ease of use of simply pasting these images in, but then Jampack generates almost 20 images sizes, which takes a long time.

**Comment by georges-gomes** [comment]
Yep, was on the plan, will do soon

**Comment by georges-gomes** [comment]
Done in version `0.14.0`

2 options added

`srcset_max_width`
and
`max_width`

Demo here: https://jampack.divriots.com/features/images-max-width/
