### ISSUE TITLE
Add support for multiple sources of the <picture> element

### ISSUE THREAD

**Issue by MrMacStripe** [divriots/jampack#90]
I have multiple use cases for using different pictures depending on the orientation of the screen. For example a background image in a hero section can be served in landscape and portrait format. 

Right now only one source is supported, the other one is being deleted by jampack.

**Comment by georges-gomes** [comment]
Do you mind sharing a `<picture>` example?

If the image is above-the-fold and no transparency then it's converted into a progressive jpeg and all sources are deleted.

But I can't find a use case where only one source stays.

With your example I can hopefully reproduce and try to fix it.
Maybe I will also be able add support for sources with `media` for proper optimisation. Which is what you most likely have...

**Comment by georges-gomes** [comment]
Made an improvement to keep the original `<source>` element as priority. Specially for art direction.
Next step will be to optimise these source as well. Today only the `<img>` that is optimised with additional sources.
For the TODO list

Thanks for reporting
