### ISSUE TITLE
Add option to skip svg

### ISSUE THREAD

**Issue by MrMacStripe** [divriots/jampack#91]
Lot's of svg do not need to be optimised. It would be very helpful if we could skip optimisation of svgs in the config.

**Comment by ZakkProjects** [comment]
For a quick workaround you can use CLI option --exclude
`jampack ./dist --exclude **/*.svg`

**Comment by georges-gomes** [comment]
New option available to disable svg optimizations.

Version `0.14.2+`

To be released
